version: "3.8"

services:
  backend:
    build:
      context: ./
    image: pueblo-azul/backend
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command:
    - nodemon
    - --inspect=0.0.0.0:9229
    - src/index.js
